
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Chefio
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: startup.sh
      timeout: 300
      runas: ec2-user
  