apiVersion: v1
kind: PersistentVolume
metadata:
  name: chefio-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/minikube-host/utibeabasi/Documents/Portfolio Projects/Chefio/backend/api/public"
  