---
- name: Install docker
  hosts: all
  become: yes
  
  tasks:      
    - name: Install pre-requisite packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        

    - name: Add Docker CE repo
      get_url:
        url: https://yum.dockerproject.org/repo/main/centos/7/
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum: name=docker state=latest

    - name: Start and enable the Docker daemon
      service: name=docker state=started enabled=yes